### ISSUE TITLE
do spark-submit job cause spark worker exited due to a missing qsql jar exception

### ISSUE THREAD

**Issue by louis83** [Qihoo360/Quicksql#19]
when i do this command "./spark-submit --master spark://master_url:7077 --deploy-mode cluster --class com.qihoo.qsql.CsvJoinWithEsExample qsql-example-0.5.jar" , then show the following exception:

Exception in thread "main" java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.spark.deploy.worker.DriverWrapper$.main(DriverWrapper.scala:65)
at org.apache.spark.deploy.worker.DriverWrapper.main(DriverWrapper.scala)
Caused by: java.lang.NoClassDefFoundError: com/qihoo/qsql/utils/PropertiesReader
at com.qihoo.qsql.env.RuntimeEnv.(RuntimeEnv.java:17)
at com.qihoo.qsql.CsvJoinWithEsExample.main(CsvJoinWithEsExample.java:11)
... 6 more
Caused by: java.lang.ClassNotFoundException: com.qihoo.qsql.utils.PropertiesReader
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 8 more

**Comment by Functor10** [comment]
It is recommended that you execute example via the script `run-example com.qihoo.qsql.CsvJoinWithEsExample`. Executing example by `spark-submit` may fail to load related Quicksql jars. In addition, could you please join the QQ group, we will provide more timely technical support.

**Comment by louis83** [comment]
> It is recommended that you execute example via the script `run-example com.qihoo.qsql.CsvJoinWithEsExample`. Executing example by `spark-submit` may fail to load related Quicksql jars. In addition, could you please join the QQ group, we will provide more timely technical support.

**Comment by louis83** [comment]
> It is recommended that you execute example via the script `run-example com.qihoo.qsql.CsvJoinWithEsExample`. Executing example by `spark-submit` may fail to load related Quicksql jars. In addition, could you please join the QQ group, we will provide more timely technical support.

Does it mean that it can only be run locally?
