### ISSUE TITLE
An exception occurred while executing a statement containing aggregate functions

### ISSUE THREAD

**Issue by julian-cn** [Qihoo360/Quicksql#208]
## Versions

0.7.0 (7bc1facd0aa586cdc8f3bd339016e8cafae05814)

## Describe the bug

通过 JDBC 执行带有聚合函数的语句时，会出现异常：java.lang.IndexOutOfBoundsException。

## To Reproduce

1. 在 MySQL (v5.7.29) 中准备数据表

```sql
-- Create a table
CREATE TABLE qsql.`Product` (
  `id` int(11) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `category` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert 5 records
INSERT INTO qsql.Product (id,price,category) VALUES (1,11.25,1),(2,15.00,1),(3,10.50,2),(4,8.16,2),(5,9.8,2);
```

2. 使用 `metadata-extract.sh` 导入元数据
3. 启动 qsql-server
4. 使用 DBeaver 通过 jdbc 连接 qsql-server 执行汇总查询

```sql
SELECT category, AVG(price) A, SUM(price) S FROM qsql.Product GROUP BY category;
```

5. 检查异常信息

## Expected behavior

正常情况下应该返回结果集。

## Actual behavior

出现异常信息：IndexOutOfBoundsException: Index: 1, Size: 1

## Full Output Logs

```log
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.Collections$SingletonList.get(Collections.java:4815)
	at com.qihoo.qsql.org.apache.calcite.rel.core.AggregateCall.toString(AggregateCall.java:310)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.qihoo.qsql.org.apache.calcite.rel.AbstractRelNode$RelDigestWriter.done(AbstractRelNode.java:468)
	at com.qihoo.qsql.org.apache.calcite.rel.AbstractRelNode.explain(AbstractRelNode.java:311)
	at com.qihoo.qsql.org.apache.calcite.rel.AbstractRelNode.computeDigest(AbstractRelNode.java:392)
	at com.qihoo.qsql.org.apache.calcite.rel.AbstractRelNode.recomputeDigest(AbstractRelNode.java:355)
	at com.qihoo.qsql.org.apache.calcite.plan.hep.HepPlanner.addRelToGraph(HepPlanner.java:821)
	at com.qihoo.qsql.org.apache.calcite.plan.hep.HepPlanner.addRelToGraph(HepPlanner.java:810)
	at com.qihoo.qsql.org.apache.calcite.plan.hep.HepPlanner.setRoot(HepPlanner.java:153)
	at com.qihoo.qsql.plan.QueryProcedureProducer.optimizeLogicalPlan(QueryProcedureProducer.java:205)
	at com.qihoo.qsql.plan.QueryProcedureProducer.createQueryProcedure(QueryProcedureProducer.java:95)
	at com.qihoo.qsql.api.DynamicSqlRunner.createQueryPlan(DynamicSqlRunner.java:65)
	at com.qihoo.qsql.api.DynamicSqlRunner.sql(DynamicSqlRunner.java:79)
	at com.qihoo.qsql.server.QuicksqlServerMeta.getExecuteResultSet(QuicksqlServerMeta.java:835)
	at com.qihoo.qsql.server.QuicksqlServerMeta.prepareAndExecute(QuicksqlServerMeta.java:799)
	at org.apache.calcite.avatica.remote.LocalService.apply(LocalService.java:206)
	at org.apache.calcite.avatica.remote.Service$PrepareAndExecuteRequest.accept(Service.java:927)
	at org.apache.calcite.avatica.remote.Service$PrepareAndExecuteRequest.accept(Service.java:879)
	at org.apache.calcite.avatica.remote.AbstractHandler.apply(AbstractHandler.java:94)
	at org.apache.calcite.avatica.remote.JsonHandler.apply(JsonHandler.java:52)
	at org.apache.calcite.avatica.server.AvaticaJsonHandler.handle(AvaticaJsonHandler.java:130)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at com.qihoo.qsql.server.QuicksqlServerMeta.getExecuteResultSet(QuicksqlServerMeta.java:856)
	at com.qihoo.qsql.server.QuicksqlServerMeta.prepareAndExecute(QuicksqlServerMeta.java:799)
	at org.apache.calcite.avatica.remote.LocalService.apply(LocalService.java:206)
	at org.apache.calcite.avatica.remote.Service$PrepareAndExecuteRequest.accept(Service.java:927)
	at org.apache.calcite.avatica.remote.Service$PrepareAndExecuteRequest.accept(Service.java:879)
	at org.apache.calcite.avatica.remote.AbstractHandler.apply(AbstractHandler.java:94)
	at org.apache.calcite.avatica.remote.JsonHandler.apply(JsonHandler.java:52)
	at org.apache.calcite.avatica.server.AvaticaJsonHandler.handle(AvaticaJsonHandler.java:130)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.Collections$SingletonList.get(Collections.java:4815)
	at com.qihoo.qsql.org.apache.calcite.rel.core.AggregateCall.toString(AggregateCall.java:310)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.qihoo.qsql.org.apache.calcite.rel.AbstractRelNode$RelDigestWriter.done(AbstractRelNode.java:468)
	at com.qihoo.qsql.org.apache.calcite.rel.AbstractRelNode.explain(AbstractRelNode.java:311)
	at com.qihoo.qsql.org.apache.calcite.rel.AbstractRelNode.computeDigest(AbstractRelNode.java:392)
	at com.qihoo.qsql.org.apache.calcite.rel.AbstractRelNode.recomputeDigest(AbstractRelNode.java:355)
	at com.qihoo.qsql.org.apache.calcite.plan.hep.HepPlanner.addRelToGraph(HepPlanner.java:821)
	at com.qihoo.qsql.org.apache.calcite.plan.hep.HepPlanner.addRelToGraph(HepPlanner.java:810)
	at com.qihoo.qsql.org.apache.calcite.plan.hep.HepPlanner.setRoot(HepPlanner.java:153)
	at com.qihoo.qsql.plan.QueryProcedureProducer.optimizeLogicalPlan(QueryProcedureProducer.java:205)
	at com.qihoo.qsql.plan.QueryProcedureProducer.createQueryProcedure(QueryProcedureProducer.java:95)
	at com.qihoo.qsql.api.DynamicSqlRunner.createQueryPlan(DynamicSqlRunner.java:65)
	at com.qihoo.qsql.api.DynamicSqlRunner.sql(DynamicSqlRunner.java:79)
	at com.qihoo.qsql.server.QuicksqlServerMeta.getExecuteResultSet(QuicksqlServerMeta.java:835)
	... 16 more
```

## Additional context

使用了外部 MySQL 作为元数据存储。

**Comment by fangyuefy** [comment]
Hello, the problem has been fixed, please use the latest version to test，thank you for your support！
