### ISSUE TITLE
0.6 的./run-example com.qihoo.qsql.CsvJoinWithEsExample 报错

### ISSUE THREAD

**Issue by xhmz** [Qihoo360/Quicksql#59]
2019-08-27 10:11:06,781 [main] ERROR - org.apache.calcite.sql.validate.SqlValidatorException: Column 'name' not found in table 'depts'
2019-08-27 10:11:06,782 [main] ERROR - org.apache.calcite.runtime.CalciteContextException: From line 1, column 126 to line 1, column 129: Column 'name' not found in table 'depts'
Exception in thread "main" com.qihoo.qsql.exception.ParseException: Error When Validating: org.apache.calcite.runtime.CalciteContextException: From line 1, column 126 to line 1, column 129: Column 'name' not found in table 'depts'
	at com.qihoo.qsql.plan.QueryProcedureProducer.buildLogicalPlan(QueryProcedureProducer.java:174)
	at com.qihoo.qsql.plan.QueryProcedureProducer.createQueryProcedure(QueryProcedureProducer.java:90)
	at com.qihoo.qsql.api.DynamicSqlRunner.createQueryPlan(DynamicSqlRunner.java:65)
	at com.qihoo.qsql.api.DynamicSqlRunner.sql(DynamicSqlRunner.java:79)
	at com.qihoo.qsql.CsvJoinWithEsExample.main(CsvJoinWithEsExample.java:24)
Caused by: org.apache.calcite.tools.ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 1, column 126 to line 1, column 129: Column 'name' not found in table 'depts'
	at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:190)
	at com.qihoo.qsql.plan.QueryProcedureProducer.buildLogicalPlan(QueryProcedureProducer.java:169)
	... 4 more
Caused by: org.apache.calcite.runtime.CalciteContextException: From line 1, column 126 to line 1, column 129: Column 'name' not found in table 'depts'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:787)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:772)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:4776)
	at org.apache.calcite.sql.validate.DelegatingScope.fullyQualify(DelegatingScope.java:439)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visit(SqlValidatorImpl.java:5637)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visit(SqlValidatorImpl.java:5619)
	at org.apache.calcite.sql.SqlIdentifier.accept(SqlIdentifier.java:334)
	at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:134)
	at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:101)
	at org.apache.calcite.sql.SqlOperator.acceptCall(SqlOperator.java:859)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visitScoped(SqlValidatorImpl.java:5655)
	at org.apache.calcite.sql.validate.SqlScopedShuttle.visit(SqlScopedShuttle.java:50)
	at org.apache.calcite.sql.validate.SqlScopedShuttle.visit(SqlScopedShuttle.java:33)
	at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:138)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.expand(SqlValidatorImpl.java:5226)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateJoin(SqlValidatorImpl.java:3092)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3029)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3290)
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:973)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:949)
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:216)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:924)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:628)
	at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:188)
	... 5 more
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Column 'name' not found in table 'depts'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)
	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:572)
	... 31 more

**Comment by GaoShengLi** [comment]
这个问题应该是你没有在qsql目录下去执行，启动过程需要在qsql的data目录下Read schema。
在qsql目录下执行sh bin/run-example com.qihoo.qsql.CsvJoinWithEsExample 应该可以消除这个问题，但是我这边遇到了包冲突问题。

**Comment by xhmz** [comment]
我是按照 readme 操作的～～

**Comment by francis-du** [comment]
@xhmz 你可以用这个Docker镜像来体验Quick SQL：https://hub.docker.com/r/francisdu/quicksql
