### ISSUE TITLE
按照集群环境部署向导无法启动测试环境

### ISSUE THREAD

**Issue by GaoShengLi** [Qihoo360/Quicksql#63]
配置好了
Java >= 1.8
Spark >= 2.2
的环境，下载了官方的release包，也配置好了base-env.sh的环境变量，但是每次启动都报下面的包冲突错误“Incompatible Jackson version: 2.10.0-pr1”，但2.10.0-pr1，自己构建排除了jackson-databind其他version的间接依赖还是不行，如下：

```
sh bin/run-example com.qihoo.qsql.CsvJoinWithEsExample
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
Elasticsearch Embedded Server is starting up, waiting....
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/qsql-0.6/lib/slf4j-log4j12-1.7.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/spark-2.3.3-bin-hadoop2.7/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Elasticsearch Embedded Server has started!! Your query is running...
Input: SELECT * FROM depts INNER JOIN (SELECT * FROM student WHERE city in ('FRAMINGHAM', 'BROCKTON', 'CONCORD')) FILTERED ON depts.name = FILTERED.type
2019-08-29 10:00:43,446 [main] INFO  - The SQL that is ready to execute is:
SELECT * FROM depts INNER JOIN (SELECT * FROM student WHERE city in ('FRAMINGHAM', 'BROCKTON', 'CONCORD')) FILTERED ON depts.name = FILTERED.type
2019-08-29 10:00:43,896 [main] INFO  - Read schema from manual schema, schema or path is: inline:
{
  "version": "1.0",
  "defaultSchema": "QSql",
  "schemas": [{
      "type": "custom",
      "name": "custom_name",
      "factory": "org.apache.calcite.adapter.csv.CsvSchemaFactory",
      "operand": {
        "directory": ""
      },
      "tables": [{
        "name": "depts",
        "type": "custom",
        "factory": "org.apache.calcite.adapter.csv.CsvTableFactory",
        "operand": {
          "file": "/usr/local/qsql-0.6/data/sales/DEPTS.csv",
          "flavor": "scannable"
        },
        "columns": [{
            "name": "deptno:int"
          },
          {
            "name": "name:string"
          }
        ]
      }]
    },
    {
      "type": "custom",
      "name": "student_profile",
      "factory": "org.apache.calcite.adapter.elasticsearch.ElasticsearchCustomSchemaFactory",
      "operand": {
        "coordinates": "{'localhost': 9025}",
        "userConfig": "{'bulk.flush.max.actions': 10, 'bulk.flush.max.size.mb': 1,'esUser':'username','esPass':'password'}",
        "index": "student"
      },
      "tables": [{
        "name": "student",
        "factory": "org.apache.calcite.adapter.elasticsearch.ElasticsearchTableFactory",
        "operand": {
          "dbName": "student_profile",
          "tableName": "student",
          "esNodes": "localhost",
          "esPort": "9025",
          "esUser": "username",
          "esPass": "password",
          "esScrollNum": "246",
          "esIndex": "student"
        },
        "columns": [{
            "name": "city:string"
          },
          {
            "name": "province:string"
          },
          {
            "name": "digest:int"
          },
          {
            "name": "type:string"
          },
          {
            "name": "stu_id:string"
          }
        ]
      }]
    }
  ]
}
2019-08-29 10:00:45,749 [main] INFO  - Running Spark version 2.3.3
2019-08-29 10:00:48,329 [main] WARN  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2019-08-29 10:00:48,420 [main] INFO  - Submitted application: spark-mixed-app
2019-08-29 10:00:48,537 [main] INFO  - Changing view acls to: hadu
2019-08-29 10:00:48,538 [main] INFO  - Changing modify acls to: hadu
2019-08-29 10:00:48,539 [main] INFO  - Changing view acls groups to:
2019-08-29 10:00:48,540 [main] INFO  - Changing modify acls groups to:
2019-08-29 10:00:48,541 [main] INFO  - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(hadu); groups with view permissions: Set(); users  with modify permissions: Set(hadu); groups with modify permissions: Set()
2019-08-29 10:00:48,648 [main] INFO  - Successfully started service 'sparkDriver' on port 55630.
2019-08-29 10:00:48,687 [main] INFO  - Registering MapOutputTracker
2019-08-29 10:00:48,724 [main] INFO  - Registering BlockManagerMaster
2019-08-29 10:00:48,729 [main] INFO  - Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
2019-08-29 10:00:48,730 [main] INFO  - BlockManagerMasterEndpoint up
2019-08-29 10:00:48,745 [main] INFO  - Created local directory at /private/var/folders/92/nxg69z853sn_tpz_pnlgfnpr0000gn/T/blockmgr-0489fdf5-83a5-49ce-90f7-856d6d1b5872
2019-08-29 10:00:48,782 [main] INFO  - MemoryStore started with capacity 2004.6 MB
2019-08-29 10:00:48,804 [main] INFO  - Registering OutputCommitCoordinator
2019-08-29 10:00:48,923 [main] INFO  - Logging initialized @13567ms
2019-08-29 10:00:49,015 [main] INFO  - jetty-9.3.z-SNAPSHOT, build timestamp: unknown, git hash: unknown
2019-08-29 10:00:49,038 [main] INFO  - Started @13683ms
2019-08-29 10:00:49,072 [main] INFO  - Started ServerConnector@563392e5{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
2019-08-29 10:00:49,072 [main] INFO  - Successfully started service 'SparkUI' on port 4040.
2019-08-29 10:00:49,137 [main] INFO  - Started o.s.j.s.ServletContextHandler@22ee1ad7{/jobs,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,138 [main] INFO  - Started o.s.j.s.ServletContextHandler@4d793390{/jobs/json,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,138 [main] INFO  - Started o.s.j.s.ServletContextHandler@3a359f7c{/jobs/job,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,139 [main] INFO  - Started o.s.j.s.ServletContextHandler@279e8bc0{/jobs/job/json,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,140 [main] INFO  - Started o.s.j.s.ServletContextHandler@23ffc910{/stages,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,140 [main] INFO  - Started o.s.j.s.ServletContextHandler@35277c6c{/stages/json,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,141 [main] INFO  - Started o.s.j.s.ServletContextHandler@7a364e1c{/stages/stage,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,142 [main] INFO  - Started o.s.j.s.ServletContextHandler@7a053795{/stages/stage/json,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,142 [main] INFO  - Started o.s.j.s.ServletContextHandler@328bc067{/stages/pool,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,143 [main] INFO  - Started o.s.j.s.ServletContextHandler@337fb1a5{/stages/pool/json,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,145 [main] INFO  - Started o.s.j.s.ServletContextHandler@38b0e2a7{/storage,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,145 [main] INFO  - Started o.s.j.s.ServletContextHandler@6bdad3bb{/storage/json,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,146 [main] INFO  - Started o.s.j.s.ServletContextHandler@73eae5f{/storage/rdd,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,146 [main] INFO  - Started o.s.j.s.ServletContextHandler@4902c584{/storage/rdd/json,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,147 [main] INFO  - Started o.s.j.s.ServletContextHandler@7698a3d9{/environment,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,147 [main] INFO  - Started o.s.j.s.ServletContextHandler@4b62f1ba{/environment/json,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,148 [main] INFO  - Started o.s.j.s.ServletContextHandler@39dce2df{/executors,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,148 [main] INFO  - Started o.s.j.s.ServletContextHandler@662d3e85{/executors/json,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,149 [main] INFO  - Started o.s.j.s.ServletContextHandler@5598dff2{/executors/threadDump,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,149 [main] INFO  - Started o.s.j.s.ServletContextHandler@92b1bda{/executors/threadDump/json,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,158 [main] INFO  - Started o.s.j.s.ServletContextHandler@57bfca3a{/static,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,159 [main] INFO  - Started o.s.j.s.ServletContextHandler@56d6e2e1{/,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,160 [main] INFO  - Started o.s.j.s.ServletContextHandler@4e9695cf{/api,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,161 [main] INFO  - Started o.s.j.s.ServletContextHandler@178ebac3{/jobs/job/kill,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,161 [main] INFO  - Started o.s.j.s.ServletContextHandler@17063c32{/stages/stage/kill,null,AVAILABLE,@Spark}
2019-08-29 10:00:49,164 [main] INFO  - Bound SparkUI to 0.0.0.0, and started at http://30.50.88.62:4040
2019-08-29 10:00:49,308 [main] INFO  - Starting executor ID driver on host localhost
2019-08-29 10:00:49,335 [main] INFO  - Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 55631.
2019-08-29 10:00:49,335 [main] INFO  - Server created on 30.50.88.62:55631
2019-08-29 10:00:49,337 [main] INFO  - Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
2019-08-29 10:00:49,375 [main] INFO  - Registering BlockManager BlockManagerId(driver, 30.50.88.62, 55631, None)
2019-08-29 10:00:49,380 [dispatcher-event-loop-2] INFO  - Registering block manager 30.50.88.62:55631 with 2004.6 MB RAM, BlockManagerId(driver, 30.50.88.62, 55631, None)
2019-08-29 10:00:49,384 [main] INFO  - Registered BlockManager BlockManagerId(driver, 30.50.88.62, 55631, None)
2019-08-29 10:00:49,385 [main] INFO  - Initialized BlockManager: BlockManagerId(driver, 30.50.88.62, 55631, None)
2019-08-29 10:00:49,402 [main] INFO  - Started o.s.j.s.ServletContextHandler@2202c92f{/metrics/json,null,AVAILABLE,@Spark}
2019-08-29 10:00:50,492 [main] INFO  - Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/usr/local/qsql-0.6/spark-warehouse').
2019-08-29 10:00:50,492 [main] INFO  - Warehouse path is 'file:/usr/local/qsql-0.6/spark-warehouse'.
2019-08-29 10:00:50,503 [main] INFO  - Started o.s.j.s.ServletContextHandler@949f0d{/SQL,null,AVAILABLE,@Spark}
2019-08-29 10:00:50,503 [main] INFO  - Started o.s.j.s.ServletContextHandler@4b3eaf39{/SQL/json,null,AVAILABLE,@Spark}
2019-08-29 10:00:50,504 [main] INFO  - Started o.s.j.s.ServletContextHandler@f73a7cf{/SQL/execution,null,AVAILABLE,@Spark}
2019-08-29 10:00:50,504 [main] INFO  - Started o.s.j.s.ServletContextHandler@4198921f{/SQL/execution/json,null,AVAILABLE,@Spark}
2019-08-29 10:00:50,506 [main] INFO  - Started o.s.j.s.ServletContextHandler@328e687e{/static/sql,null,AVAILABLE,@Spark}
2019-08-29 10:00:51,302 [main] INFO  - Registered StateStoreCoordinator endpoint
2019-08-29 10:00:51,337 [main] INFO  - Elasticsearch Hadoop v6.2.4 [0dadc1ea14]
2019-08-29 10:00:54,332 [main] INFO  - Pruning directories with:
2019-08-29 10:00:54,337 [main] INFO  - Post-Scan Filters: (length(trim(value#10, None)) > 0)
2019-08-29 10:00:54,342 [main] INFO  - Output Data Schema: struct<value: string>
2019-08-29 10:00:54,353 [main] INFO  - Pushed Filters:
2019-08-29 10:00:54,491 [main] INFO  - Code generated in 30.945461 ms
2019-08-29 10:00:54,560 [main] INFO  - Stopped Spark@563392e5{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
2019-08-29 10:00:54,561 [main] INFO  - Stopped Spark web UI at http://30.50.88.62:4040
2019-08-29 10:00:54,573 [dispatcher-event-loop-7] INFO  - MapOutputTrackerMasterEndpoint stopped!
2019-08-29 10:00:54,585 [main] INFO  - MemoryStore cleared
2019-08-29 10:00:54,586 [main] INFO  - BlockManager stopped
2019-08-29 10:00:54,595 [main] INFO  - BlockManagerMaster stopped
2019-08-29 10:00:54,599 [dispatcher-event-loop-4] INFO  - OutputCommitCoordinator stopped!
2019-08-29 10:00:54,605 [main] INFO  - Successfully stopped SparkContext
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:247)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:337)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:3278)
	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2489)
	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2489)
	at org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3259)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3258)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:2489)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:2703)
	at org.apache.spark.sql.execution.datasources.csv.TextInputCSVDataSource$.infer(CSVDataSource.scala:148)
	at org.apache.spark.sql.execution.datasources.csv.CSVDataSource.inferSchema(CSVDataSource.scala:63)
	at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat.inferSchema(CSVFileFormat.scala:57)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$8.apply(DataSource.scala:203)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$8.apply(DataSource.scala:203)
	at scala.Option.orElse(Option.scala:289)
	at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:202)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:393)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:596)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:473)
	at Requirement52045.execute(Requirement52045.java:33)
	at com.qihoo.qsql.exec.result.JobPipelineResult.run(JobPipelineResult.java:39)
	at com.qihoo.qsql.CsvJoinWithEsExample.main(CsvJoinWithEsExample.java:24)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.10.0-pr1
	at com.fasterxml.jackson.module.scala.JacksonModule$class.setupModule(JacksonModule.scala:64)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:19)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:779)
	at org.apache.spark.rdd.RDDOperationScope$.<init>(RDDOperationScope.scala:82)
	at org.apache.spark.rdd.RDDOperationScope$.<clinit>(RDDOperationScope.scala)
	... 28 more
```

**Comment by James601232** [comment]
你好
看错误应该是jar包版本不兼容导致的问题，spark2.x依赖的jackson包都是2.6.x的版本，可以把环境中的jackson的包换成2.6.x版本试试，另外解决jackson版本为什么是2.10.0-pr1可以通过maven依赖树找出依赖关系。

**Comment by GaoShengLi** [comment]
感谢 @James601232 的帮助，2.10.0-pr1的包是在Quicksql中引入的，我将Quicksql中的jackson相关的包修改到2.6.5版本解决了这个问题。
