### ISSUE TITLE
启动例子失败

### ISSUE THREAD

**Issue by jzdayz** [Qihoo360/Quicksql#69]
这个是不是有问题，报错信息为表depts没有name这个列，但是打印的json日志，不是说depts有name这个列吗？

```logs
2019-09-09 16:04:09,998 [main] INFO  - Read schema from manual schema, schema or path is: inline:
{
  "version": "1.0",
  "defaultSchema": "QSql",
  "schemas": [{
      "type": "custom",
      "name": "custom_name",
      "factory": "org.apache.calcite.adapter.csv.CsvSchemaFactory",
      "operand": {
        "directory": ""
      },
      "tables": [{
        "name": "depts",
        "type": "custom",
        "factory": "org.apache.calcite.adapter.csv.CsvTableFactory",
        "operand": {
          "file": "/Users/huqingfeng/Downloads/qsql-0.6/bin/data/sales/DEPTS.csv",
          "flavor": "scannable"
        },
        "columns": [{
            "name": "deptno:int"
          },
          {
            "name": "name:string"
          }
        ]
      }]
    },
    {
      "type": "custom",
      "name": "student_profile",
      "factory": "org.apache.calcite.adapter.elasticsearch.ElasticsearchCustomSchemaFactory",
      "operand": {
        "coordinates": "{'localhost': 9025}",
        "userConfig": "{'bulk.flush.max.actions': 10, 'bulk.flush.max.size.mb': 1,'esUser':'username','esPass':'password'}",
        "index": "student"
      },
      "tables": [{
        "name": "student",
        "factory": "org.apache.calcite.adapter.elasticsearch.ElasticsearchTableFactory",
        "operand": {
          "dbName": "student_profile",
          "tableName": "student",
          "esNodes": "localhost",
          "esPort": "9025",
          "esUser": "username",
          "esPass": "password",
          "esScrollNum": "246",
          "esIndex": "student"
        },
        "columns": [{
            "name": "city:string"
          },
          {
            "name": "province:string"
          },
          {
            "name": "digest:int"
          },
          {
            "name": "type:string"
          },
          {
            "name": "stu_id:string"
          }
        ]
      }]
    }
  ]
}
2019-09-09 16:04:10,777 [main] ERROR - org.apache.calcite.sql.validate.SqlValidatorException: Column 'name' not found in table 'depts'
2019-09-09 16:04:10,778 [main] ERROR - org.apache.calcite.runtime.CalciteContextException: From line 1, column 126 to line 1, column 129: Column 'name' not found in table 'depts'
Exception in thread "main" com.qihoo.qsql.exception.ParseException: Error When Validating: org.apache.calcite.runtime.CalciteContextException: From line 1, column 126 to line 1, column 129: Column 'name' not found in table 'depts'
	at com.qihoo.qsql.plan.QueryProcedureProducer.buildLogicalPlan(QueryProcedureProducer.java:174)
	at com.qihoo.qsql.plan.QueryProcedureProducer.createQueryProcedure(QueryProcedureProducer.java:90)
	at com.qihoo.qsql.api.DynamicSqlRunner.createQueryPlan(DynamicSqlRunner.java:65)
	at com.qihoo.qsql.api.DynamicSqlRunner.sql(DynamicSqlRunner.java:79)
	at com.qihoo.qsql.CsvJoinWithEsExample.main(CsvJoinWithEsExample.java:24)
Caused by: org.apache.calcite.tools.ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 1, column 126 to line 1, column 129: Column 'name' not found in table 'depts'
	at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:190)
	at com.qihoo.qsql.plan.QueryProcedureProducer.buildLogicalPlan(QueryProcedureProducer.java:169)
	... 4 more
Caused by: org.apache.calcite.runtime.CalciteContextException: From line 1, column 126 to line 1, column 129: Column 'name' not found in table 'depts'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:787)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:772)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:4776)
	at org.apache.calcite.sql.validate.DelegatingScope.fullyQualify(DelegatingScope.java:439)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visit(SqlValidatorImpl.java:5637)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visit(SqlValidatorImpl.java:5619)
	at org.apache.calcite.sql.SqlIdentifier.accept(SqlIdentifier.java:334)
	at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:134)
	at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:101)
	at org.apache.calcite.sql.SqlOperator.acceptCall(SqlOperator.java:859)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visitScoped(SqlValidatorImpl.java:5655)
	at org.apache.calcite.sql.validate.SqlScopedShuttle.visit(SqlScopedShuttle.java:50)
	at org.apache.calcite.sql.validate.SqlScopedShuttle.visit(SqlScopedShuttle.java:33)
```

**Comment by Foster9527** [comment]
可能是执行的路径不对，导致文件路径错误，你cat /Users/huqingfeng/Downloads/qsql-0.6/bin/data/sales/DEPTS.csv，看看文件是否存在或者内容是否正确

希望可以帮助到你
