### ISSUE TITLE
Couldn't import Hive metadata

### ISSUE THREAD

**Issue by shaofengshi** [Qihoo360/Quicksql#74]
I'm using Qsql 0.6 on CentOS; My hive is working well, using MySQL as both Hive metastore and Qsql metastore (already initiated the metadata tables);

When I tried to import the table info from Hive, got an error:

 ./bin/meta-extract -p "{\"jdbcDriver\": \"com.mysql.jdbc.Driver\", \"jdbcUrl\": \"jdbc:mysql://localhost:3306/hive\", \"jdbcUser\": \"root\",\"jdbcPassword\": \"\", \"dbName\": \"default\"}" -d "hive"
2019-09-26 06:49:26,806 [main] INFO  - Input params: properties({"jdbcDriver": "com.mysql.jdbc.Driver", "jdbcUrl": "jdbc:mysql://localhost:3306/hive", "jdbcUser": "root","jdbcPassword": "", "dbName": "default"}), type(hive), filter regex(%%)
2019-09-26 06:49:26,807 [main] INFO  - Connecting server.....
2019-09-26 06:49:27,311 [main] INFO  - Connected successfully!!
2019-09-26 06:49:27,341 [main] INFO  - Insert database default successfully!!
2019-09-26 06:49:27,352 [main] INFO  - Insert table call_detail_records successfully!!
Exception in thread "main" java.lang.RuntimeException: java.sql.SQLException: Column count doesn't match value count at row 1
	at com.qihoo.qsql.metadata.MetadataClient.insertFieldsSchema(MetadataClient.java:227)
	at com.qihoo.qsql.metadata.collect.MetadataCollector.execute(MetadataCollector.java:106)
	at com.qihoo.qsql.metadata.collect.MetadataCollector.main(MetadataCollector.java:73)
Caused by: java.sql.SQLException: Column count doesn't match value count at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2683)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2144)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1379)
	at com.qihoo.qsql.metadata.MetadataClient.insertFieldsSchema(MetadataClient.java:225)

**Comment by shaofengshi** [comment]
But if I import a Mysql table, it got success:

> ./bin/./meta-extract -p "{\"jdbcDriver\": \"com.mysql.jdbc.Driver\", \"jdbcUrl\": \"jdbc:mysql://localhost:3306/test\", \"jdbcUser\": \"root\",\"jdbcPassword\": \"\"}" -d "mysql"
2019-09-26 06:52:39,715 [main] INFO  - Input params: properties({"jdbcDriver": "com.mysql.jdbc.Driver", "jdbcUrl": "jdbc:mysql://localhost:3306/test", "jdbcUser": "root","jdbcPassword": ""}), type(mysql), filter regex(%%)
2019-09-26 06:52:39,716 [main] INFO  - Connecting server.....
2019-09-26 06:52:40,199 [main] INFO  - Connected successfully!!
2019-09-26 06:52:40,233 [main] INFO  - Insert database test successfully!!
2019-09-26 06:52:40,243 [main] INFO  - Insert table sample_07 successfully!!
2019-09-26 06:52:40,299 [main] INFO  - Successfully collected metadata for 1 tables!!
2019-09-26 06:52:40,300 [main] INFO  - sample_07

**Comment by shaofengshi** [comment]
Change the log to debug level, it seems creating a table called "call_detail_records" while this table has no column.

> 2019-09-26 07:08:16,269 [main] INFO  - Connecting server.....
2019-09-26 07:08:16,811 [main] INFO  - Connected successfully!!
2019-09-26 07:08:16,825 [main] DEBUG - getBasicDatabaseInfo sql is select DB_ID, `DESC`, NAME, DB_TYPE from DBS where name ='edw'
2019-09-26 07:08:16,826 [main] DEBUG - insertBasicDatabaseInfo sql is INSERT INTO DBS(NAME, DB_TYPE, `DESC`) VALUES('edw', 'hive', 'Who am I')
2019-09-26 07:08:16,833 [main] DEBUG - insertDatabaseSchema sql is INSERT INTO DATABASE_PARAMS(DB_ID, PARAM_KEY, PARAM_VALUE) VALUES (5, 'cluster', 'default')
2019-09-26 07:08:16,833 [main] INFO  - Insert database edw successfully!!
2019-09-26 07:08:16,838 [main] DEBUG - getTableSchema sql is select DB_ID,TBL_ID,TBL_NAME from TBLS where TBL_NAME='call_detail_records'
2019-09-26 07:08:16,845 [main] DEBUG - insertTableSchema sql is INSERT INTO TBLS(DB_ID, TBL_NAME) VALUES(5, 'call_detail_records')
2019-09-26 07:08:16,845 [main] INFO  - Insert table call_detail_records successfully!!
2019-09-26 07:08:16,848 [main] DEBUG - insertFieldsSchema sql is INSERT INTO COLUMNS(CD_ID, COLUMN_NAME,TYPE_NAME,INTEGER_IDX) VALUES ()
Exception in thread "main" java.lang.RuntimeException: java.sql.SQLException: Column count doesn't match value count at row 1
	at com.qihoo.qsql.metadata.MetadataClient.insertFieldsSchema(MetadataClient.java:227)
	at com.qihoo.qsql.metadata.collect.MetadataCollector.execute(MetadataCollector.java:106)
	at com.qihoo.qsql.metadata.collect.MetadataCollector.main(MetadataCollector.java:73)

But in Hive, in this database there is no such a table:

> hive> use edw;
OK
Time taken: 1.158 seconds
hive> show tables;
OK
test_cal_dt
test_seller_type_dim
test_seller_type_dim_table
test_sites
Time taken: 0.623 seconds, Fetched: 4 row(s)

After some checking, I found this Hive table is in another database, not the "edw" that I specified;

mysql> select TBL_NAME, DB_ID from TBLS;
+-------------------------------------------------------------------------------------------+-------+
| TBL_NAME                                                                                  | DB_ID |
+-------------------------------------------------------------------------------------------+-------+
| call_detail_records                                                                       |     6 |

mysql> select * from DBS where DB_ID=6;
+-------+------+-------------------------------------------------------------------+--------+------------+------------+
| DB_ID | DESC | DB_LOCATION_URI                                                   | NAME   | OWNER_NAME | OWNER_TYPE |
+-------+------+-------------------------------------------------------------------+--------+------------+------------+
|     6 | NULL | hdfs://xxx:8020/apps/hive/warehouse/xademo.db | xademo | hive       | USER       |
+-------+------+-------------------------------------------------------------------+--------+------------+------------+

This table has columns:

hive> describe call_detail_records;
OK
phone_number        	string
phone_type          	string
in_out              	string
rec_local           	string
duration            	string
rec_date            	string
time                	string
roaming             	string
amount              	string
in_network          	string
is_promo            	string
toll_free           	string
bytes               	string
type                	string
Time taken: 0.58 seconds, Fetched: 14 row(s)

**Comment by shaofengshi** [comment]
After some debugging, I found this is a bug; When the "-r" is absent, it will try to load all tables, and then it will find there is no columns, then caused the error.

After change to using:

> ./bin/meta-extract -p "{\"jdbcDriver\": \"com.mysql.jdbc.Driver\", \"jdbcUrl\": \"jdbc:mysql://localhost:3306/hive\", \"jdbcUser\": \"root\",\"jdbcPassword\": \"\", \"dbName\": \"edw\"}" -d "hive" -r "edw"

it doesn't throw error, but has no table loaded:

> 2019-09-26 07:52:58,226 [main] DEBUG - getBasicDatabaseInfo sql is select DB_ID, `DESC`, NAME, DB_TYPE from DBS where name ='edw'
2019-09-26 07:52:58,227 [main] DEBUG - insertBasicDatabaseInfo sql is INSERT INTO DBS(NAME, DB_TYPE, `DESC`) VALUES('edw', 'hive', 'Who am I')
2019-09-26 07:52:58,233 [main] DEBUG - insertDatabaseSchema sql is INSERT INTO DATABASE_PARAMS(DB_ID, PARAM_KEY, PARAM_VALUE) VALUES (6, 'cluster', 'default')
2019-09-26 07:52:58,234 [main] INFO  - Insert database edw successfully!!
2019-09-26 07:52:58,285 [main] INFO  - Successfully collected metadata for 0 tables!!

**Comment by shaofengshi** [comment]
If provide the exact table name with "-r", it can load successfully:

./bin/meta-extract -p "{\"jdbcDriver\": \"com.mysql.jdbc.Driver\", \"jdbcUrl\": \"jdbc:mysql://localhost:3306/hive\", \"jdbcUser\": \"root\",\"jdbcPassword\": \"\", \"dbName\": \"edw\"}" -d "hive" -r "test_cal_dt"

2019-09-26 08:03:22,039 [main] INFO  - Successfully collected metadata for 1 tables!!
2019-09-26 08:03:22,040 [main] INFO  - test_cal_dt

**Comment by shaofengshi** [comment]
Besides, I found the "hive-site.xml" need to be in $SPARK_HOME/conf folder, otherwise Spark will report table not found error. Anyway, now I can run a simple sample, thanks for sharing this tool!
