### ISSUE TITLE
mysql数据库,完整表名问题

### ISSUE THREAD

**Issue by liisaxin** [Qihoo360/Quicksql#80]
完整表名格式的:database_name. table_name对吧?
单个select * from order.order_info  limit 10 这样的查询语句在命令行下报错,不知道为什么?
是`order`这个数据库名称是关键词吗?

```bash
#执行语句
./qsql -e "select * from order.order_info limit 10"
```
返回结果:
```
2019-10-10 19:17:59,768 [main] INFO  - Your SQL is 'select * from order.order_info limit 10
'
Exception in thread "main" java.lang.RuntimeException: Encountered "from order" at line 1, column 10.
Was expecting one of:
    <EOF> 
    "ORDER" ...
    "LIMIT" ...
    "OFFSET" ...
    "FETCH" ...
    "FROM" <IDENTIFIER> ...
    "FROM" <QUOTED_IDENTIFIER> ...
    "FROM" <BACK_QUOTED_IDENTIFIER> ...
    "FROM" <BRACKET_QUOTED_IDENTIFIER> ...
    "FROM" <UNICODE_QUOTED_IDENTIFIER> ...
    "FROM" "LATERAL" ...
    "FROM" "(" ...
    "FROM" "UNNEST" ...
    "FROM" "TABLE" ...
    "," ...
    "AS" ...
    <IDENTIFIER> ...
    <QUOTED_IDENTIFIER> ...
    <BACK_QUOTED_IDENTIFIER> ...
    <BRACKET_QUOTED_IDENTIFIER> ...
    <UNICODE_QUOTED_IDENTIFIER> ...
    "UNION" ...
    "INTERSECT" ...
    "EXCEPT" ...
    "MINUS" ...
    
	at com.qihoo.qsql.utils.SqlUtil.parseTableName(SqlUtil.java:26)
	at com.qihoo.qsql.launcher.ExecutionDispatcher.main(ExecutionDispatcher.java:66)
 
```

**Comment by liisaxin** [comment]
```bash
# 解决办法
./qsql -e "select * from \`order\`.order_info limit 10"

```
已经通过对sql关键子前后包含`,然后对其进行转义 \` 方式解决,谢谢!
